[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cloudmap"
version = "1.0.0rc1"
description = "Trace the blast radius of your Azure resources with style."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich>=13.0.0",
    "questionary>=2.0.0"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.scripts]
cloudmap = "cloudmap.cli:main"

[tool.ruff]
line-length = 180

[tool.ruff.lint]
ignore = ["E501", "E402", "F401", "BLE001", "F841", "C414", "C401", "FURB167", "RUF059", "RUF100", "FA100", "PLW1510", "S110"]
